global using System;
global using Awesome_Game;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Input;
global using Microsoft.Xna.Framework.Graphics;
global using Microsoft.Xna.Framework.Content;
global using System.Collections.Generic;
global using Microsoft.Xna.Framework.Audio;
global using Microsoft.Xna.Framework.Media;